### ISSUE TITLE
We need to support versioning

### ISSUE THREAD

**Issue by JekaMas** [clearmatics/autonity#118]
- [ ] Create `versioning.md` file
- [ ] Specify versioning in the file
- [ ] Specify Autonity main APIs that should be versioned
- [ ] Remove all tags from the repo
- [ ] Specify the most recent stable commit as `0.1.0` version (we should check that everything is fine with https://github.com/clearmatics/validator-dapp/issues/9 before)

Context is [here](https://github.com/clearmatics/www-engineering/blob/master/versioning.Rmd)

**Comment by Shirikatsu** [comment]
We'll version the Autonity client and the Tendermint implementation independently. I'll leave the versioning of the Tendermint implementation to your judgement. 

Current plans for the Autonity client versioning will begin at v1.0.0 on first feature-complete release of the client.

As noted if your link, we'll continue to use symver going forward.

**Comment by aneequesafdar** [comment]
Any specific reason to have versioning for Tendermint implementation separately? Surely, Tendermint implementation will be one of the features of Autonity as it not possible to have Tendermint without Autonity.

**Comment by Shirikatsu** [comment]
So I had a brief chat with George about it and we'll stick to a single versioning scheme for the entire project. It would be messy seeing as we're only intending to release a single binary which is what we're really versioning for.

The rationale was that in my mind there could be client changes that will increment the version of autonity that don't affect Tendermint. It's more about attempting to keep things clean and having independent referencing since development is happening independently.

An example of why it could be useful is if external entities wanting to plug our version of Tendermint into their client but not want to use Autonity.

**Comment by shapeshed** [comment]
Agree - we should make sure any build and release process takes account of tagging. Ideally we could automate pushing a tagged and signed docker image into docker hub but that's one for DevOps. 

I want to be able to do this for each version and referencing tagged versions would feed into automated deployments too. 
```
docker pull clearmatics/autonity:0.1.0
```
