### ISSUE TITLE
Tendermint acceptance criteria

### ISSUE THREAD

**Issue by yazzaoui** [clearmatics/autonity#228]
# Tendermint Acceptance Criterias

## Protocol :

Implementation of the protocol described [here](https://arxiv.org/pdf/1807.04938.pdf), with the following taken into accounts :
- Quorum : Q = ceil((2*N)/3)
- Byzantine Threshold : F = floor((N-1)/3)
- Proposer selection: round-robin, same as IBFT
- isValid() implementation must only allow valid and able to be inserted blocks.
- L55 amendment/precision: ```Upon received F+1 <Prevote,hp,round,*,*> OR F+1 <Precommit,hp,round,*,*> with round > roundP then startRound(round)```

## Implementation :

- Changes should only be brought to the consensus package, any modification outside `./consensus/tendermint` will need to be thoroughly justified.
- Implementation must keep light client compatibility.
- Implementation must keep Soma compatibility.
- Unresolved following issues raised during the first review must be resolved:
  - [Double signing vulnerability for future round change](https://github.com/clearmatics/autonity/pull/185#discussion_r309619554)
  - [TotalSize() implementation](https://github.com/clearmatics/autonity/pull/185#discussion_r309733019)
- Synchronisation: All received consensus messages **from** the latest round with `F+1 <Prevote,hp,round,*,*> OR F+1 <Precommit,hp,round,*,*>` must be transmitted to newly connected validators.

## Automated testing
Integration tests and unit test coverage is left to the team best judgment.
Automated tests should be able to demonstrate at the minimum the following scenarios:
- Correct proposal trigger a prevote and move step to propose step (L22)
- Received quorum of prevote trigger precommit (L28 & L36)
- Received quorum of precommit trigger decision (L49)
- Invalid block(with double signed transaction, bad roothash, wrong extradata) proposed trigger a round change.
- Block received by a validator and a non-validator can't get inserted with less than Q valid precommit seals.
- Invalid votes are discarded (bad block hash) 

## Manual testing
Following scenarios must be manually tested:
- Stability over 72 hours on a cluster of 10 validators with 100tx/sec: No memory leak and no stalling
- Compatibility with Soma contract: adding and removing validators.
- Recovery of a cluster of 7 validators where 2 validators were offline for 3 hours.
- Bootstrapping of a network of 7 validators with 1 node started per hour.

## Performance requirements

- Block mining rate should average 1 block/sec .
- +/- 20% Max Transaction per seconds compared to IBFT implementation for clusters of 4/7/10/13/15 nodes.
- Less than 2 mins transaction processing latency for clusters of 4/7/10/13/15 nodes.

**Comment by aneequesafdar** [comment]
I think the last bullet point for Protocol should not be part of the acceptance criteria because we don't fully understand its impact on the rest of the consensus algorithm. After some discussion with the team, we decided that we will try to find in Tendermint codebase if they implement L55 and open an issue with the specification on Tendermint repo about the L55 vulnerability.

First bullet point of implementation means that we cannot write e2e tests, some which have already been written and already discovered race conditions in the codebase, how is it in the best interest of Clearmatics to delete them? How else can we test for liveness and safety properties? Which is very important to test.

Pulling from upstream should not be too much work as explained by @JekaMas and @screwyprof, that pulling and merging from upstream once or twice a year should be feasible with 1 or 2 of work.

Last bullet point of Implementation is somewhat implemented by WAL, however, instead of sending message to newly connected peer it only resends messages from wal based on a timer and if the network has stalled. I think it could be modified to this case.

Also, this sentence doesn't make sense `All received consensus messages from the latest round with F+1 <Prevote,hp,round,*,*> OR F+1 <Precommit,hp,round,*,*>`  you say to send all messages in the first part f+1 prevotes or precommits for the current round, what happens if those nodes don't have f+1 messages (it may also be the reason they are stuck). 

It is simpler to say to send all messages of the for the current height. to the newly connected peer, and we would need to send all of the messages from the current height because some condition in the tendermint algorithm depends on messages from previous rounds. To reduce message complexity I think it might be best to send current and old round states in one message, although it will increase the message size.

I think we need to focus on writing some test for the code we have currently, as it is quite substantial, and tests are invaluable in finding race conditions which usually are hardest or near impossible to detect by just reviewing code, we shouldn't add more features without having some confidence in the current codebase.

I don't think we will not have enough time to implement some new features, test them and review to "good" standard, some of the acceptance criteria will need some compromisation.

**Comment by aneequesafdar** [comment]
I am not sure how we will substantiate the manual testing, how would we detect a memory leak and a network may stall then restart and we may not about it because we cannot watch the network for 72 hours straight.

Performance requirements first bullet point can only happen if on average no node is byzantine, because the moment one node is byzantine due to round change we would have timeouts which will impact the block mining time. As testing during benchmarking, sure the number of transaction in a block will have an impact of the time of block being mined, this will be even more problematic because we test for correct state after receiving the proposal. While the rest of the performacne requirements seem machine dependent.
