### ISSUE TITLE
PoS integration missing features

### ISSUE THREAD

**Issue by yazzaoui** [clearmatics/autonity#362]
This issue is about  PoS integration and listing changes that need to be made.

**Comment by aesmonty** [comment]
### Introduction
There are a group of features that we are fully or partially missing to have a basic but functional version of PoS over BFT. In short, these are:

1. Committee selection, top-N validators by voting power.
2. Consensus votes weighted by voting power.
3. Proposer selection weighted by stake (i.e. weighted round-robin).

### Description
Let's go over each of these features to reflect their level of completeness and what still needs to be done.

#### Committee Selection

- Implemented functionality at the [Autonity contract level](https://github.com/clearmatics/autonity/blob/master/contracts/autonity/contract/contracts/Autonity.sol#L374).
- Missing integration with the client through a contract call in `autonity.go`.

#### Weighted Votes

- Block header structure changed, to accommodate the PoS requirements. In particular, it was added a `Committee` field which contains the `Address` and `VotingPower` of each committee member.
- We are missing the consensus weighting in message sets and quorum calculations. (expand)
- This feature has the integration of the committee selection as a **prerequisite**.

#### Proposer Selection

- Not implemented. Currently, we are using simple round-robin at the client level.
- This feature still needs some time for research pre-development as this is not a trivial problem. To get an idea of its challenges, have a look at the implementation and analysis by [Tendermint](https://docs.tendermint.com/master/spec/reactors/consensus/proposer-selection.html).

**Comment by Jason-Zhangxin-Chen** [comment]
- Committee selection, top-N validators by voting power.

QQ: In term of liveness, selection should involved height and round as two extra factors to pick up members. Simply take top-N by voting power(stake token) might harm the liveness when top-N nodes crashed. 

QQ: In term of fairness, do we need to apply a weighted round-robin on the commitee selection? Since some node might have very low power to be selected as member of the commitee.

- Consensus votes weighted by voting power.
QQ: How does the totall of voting power calculated on each block height? Is it counted by each members' voting power of the current commitee?  If so, what is the interval to renew the commitee?

- Proposer selection weighted by stake (i.e. weighted round-robin).
QQ: The proposer selection should also take height and round as extra factors to avoid single point failure.

- Fair reward assignation.
QQ: If we apply weighted round-robin to select commitee and proposer, and regarding to the requirement to distribute reward only to those commitee members who voted on time. Since different node might have different view of the consensus message states, how to guarantee the distribution of reward to the same set(view) of memebers who voted on time? Can we just simply distribute the reward to the members in the commitee which share it by their voting power?

**Comment by Jason-Zhangxin-Chen** [comment]
@yazzaoui @aneequesafdar , proposer selection by Weighted Round-Robin is usually a state-full algorithm which depends on the context of its internal state.  There are two place client side and contract side to implement it. To implement it in client side, the state of this algorithm might need to be synced between nodes in case of node join into the network. To implement it in contract side, before voting a new block, getProposer(Height, Round) need to change the WRR algorithm state which stored in blockchain, but at this point, it is not possible to change it since it is read only untill we finalized a new block. I am trying to find a state-less WRR algorithm. Otherwise we might first implement a simple round-robin at this moment.
