### ISSUE TITLE
Proposer selection mechanism

### ISSUE THREAD

**Issue by yazzaoui** [clearmatics/autonity#413]
- Design deterministic proposer selection algorithm weighted by stake `getProposer(height, round)`
- Implement in solidity

**Comment by Jason-Zhangxin-Chen** [comment]
- Weighted round robin(WRR) is a scheduling algorithm, we are going to use it as proposer election algorithm base on a sorted top N numbers of validator by their stake, this set is so called committee. The committee renewal will happen per each new block since after new block's finalization, the stake balance would change by reward distribution. 

- To keep it simple, autonity was design to implement it base on autonity contract since it guarantee the consistent view of the context.

- Base on some research, WRR has both state-full and state-less styles. For example a state-full design in Tendermint’s proposer election: https://docs.tendermint.com/master/spec/reactors/consensus/proposer-selection.html and http://kb.linuxvirtualserver.org/wiki/Weighted_Round-Robin_Scheduling

- In Tendermint, the WRR is a state-full algorithm which base on a priority queue, each call of get_proposer(height, round) would change the internal state of the WRR by shifting the position of nodes to promise a fair-scheduling. But Tendermint again does not cover the scenario of state recovery from a disaster which means engineering need extra effort to keep the consistency for the determination, and the algorithm was not formal verified yet said by their R&D.

- To implement a state-full WRR base on autonity contract is easy, but in our case, the timing of calling get_proposer(height, round) is at a new block preparation phase, where in the time line, there is no chance to change the view of blockchain where our autonity contract’s storage are stored. It means the internal state managed by WRR cannot be updated and the fair scheduling will fail too.

- So, we are implementing a state-less WRR for proposer election in autonity contract. Committee = top_N_stake(validator_set);  N is configurable in contract, the algorithm is described as below:
![1226195463](https://user-images.githubusercontent.com/54585152/75329903-64484880-5878-11ea-9787-8b02205ca5f3.jpg)

The test report:
`proposed times:  6048000
Commitee voting power list:  [3523000, 4171000, 4302000, 6901000, 8684000, 13805000]
1 sha with sum WRR    hits:  [514458, 608347, 628766, 1008047, 1271019, 2017363]
1 sha with mul WRR    hits:  [516031, 609927, 629570, 1008771, 1267271, 2016430]
2 sha with sum WRR    hits:  [515902, 609924, 629521, 1007589, 1265926, 2019138]
2 sha with mul WRR    hits:  [515872, 609701, 628074, 1009703, 1267941, 2016709]
        expected hit ratio: % [8.512540472623593, 10.078287343546126, 10.394819504180157, 16.674720920117913, 20.98294109119026, 33.356690668341955]
1 sha with sum WRR   ratio: % [8.50625, 10.058647486772486, 10.396263227513227, 16.667443783068784, 21.015525793650795, 33.35586970899471]
1 sha with mul WRR   ratio: % [8.532258597883597, 10.084771825396825, 10.409556878306878, 16.679414682539683, 20.953554894179895, 33.34044312169312]
2 sha with sum WRR   ratio: % [8.530125661375662, 10.084722222222222, 10.408746693121692, 16.659871031746032, 20.93131613756614, 33.385218253968254]
2 sha with mul WRR   ratio: % [8.52962962962963, 10.081035052910053, 10.384821428571428, 16.694824735449735, 20.964632936507936, 33.34505621693122]
`
By comparing the expected scheduling ratio and the actual scheduling ratio, their delta trend to infinitesimal by the time line extends.

**Comment by JekaMas** [comment]
What exact properties do we want to achieve?

**Comment by Jason-Zhangxin-Chen** [comment]
> What exact properties do we want to achieve?
Hi Eugene, yes it is about to implement a proposer election algorithm weigthed by stake or voting power, and it is adaptable with current autonity. This is my report on the WRR research and pre-development, the teammate here can review and discuss it, then we can land it into production.

**Comment by JekaMas** [comment]
I'm talking about algorithm properties, eg:
- Availability (or liveness)
- Unbiasability (or bias-resistance)
- Public-Verifiability
- Unpredictability

**Comment by JekaMas** [comment]
It's hard to say something about the algorithm if we haven't defined it's properties and goals.

**Comment by JekaMas** [comment]
basic properties are

- Availability (or liveness) - any single participant (or colluding participants) should
not be able to prevent a selection process.
- Unpredictability - any single participant (or colluding participants) should not be
able to obtain any information about future selection values.
- Unbiasability (or bias-resistance) - any single participant (or colluding participants)
should not be able to influence proposal selection to their advantage.
- Public-Verifiability - third parties should be able to verify the correctness of generated by the algorithm value using public information only.

**Comment by differentialderek** [comment]
Just to be sure—the committee selection algorithm is also weighted, right? I'm guessing that this algorithm will, most of the time, only have to choose one validator per block (assuming most of the validators are well-connected and online). So such a weighting would be useful in that (1) higher-weighted validators get chosen first more frequently over time, and (2) if lower-weighted nodes are offline then the higher-weighted nodes have a higher chance of getting the proposer fee for that particular block.

So I would say one of the properties we should be sure to have is a selection mechanism that allows for the proposer from the first round to be anyone, with probability in the higher-weighted nodes' favour. E.g. It shouldn't always start with the heaviest node.

**Comment by Jason-Zhangxin-Chen** [comment]
@JekaMas, Eugene, Thank you so much for those valueable comments that I missed in the inroduction. I leave my understanding on the findings below:

- Availability (or liveness) - any single participant (or colluding participants) should not be able to prevent a selection process.
> The proposing process is isolated by each committee members, each node will only base on its own view(height of chain) of the blockchain to proceed the election process, for those consensus msg of whom's block is not synced with latest height, they are discarded.

- Unpredictability - any single participant (or colluding participants) should not be able to obtain any information about future selection values.
> The committee_set as one of the input of the election is a sorted list by stake. It is renewed per block since the reward distribution will take it into stake balance. Nodes are sure about the proposer of current round, they does not know the future round's proposer since no one can predict the TX fees (rewards) in the future blocks. In a permissioned network we can also prevent this by adding network governance like public chain did.

- Unbiasability (or bias-resistance) - any single participant (or colluding participants) should not be able to influence proposal selection to their advantage.
> This is a very good finding. Tendermint is a BFT series consensus, it is assumed that: N = 3 F + 1; if the number of colluding participants exceed F, then Tendermint will fail for sure. I think in the block verification phase, honest node can address this attack, but they have no chance to rollback those colluding participants. We need to think about it carefully, WRR does not cover this requirement indeed, but we have to re-think about it now. Personally, I think it should be covered by network governance features. 

- Public-Verifiability - third parties should be able to verify the correctness of generated by the algorithm value using public information only.
> The view used for proposer election is stored at autonity contract, the algorithm have the idempotence under a specific view. In the third parties monitoring system, they can playback the view at any height base on autonity contract.

**Comment by differentialderek** [comment]
LGTM

**Comment by SherifSK** [comment]
@Jason-Zhangxin-Chen, @JekaMas, @yazzaoui  

Great work guys. I suggest creating an ADR [here](https://github.com/clearmatics/architecture) for the proposer selection mechanism
